on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore dependencies
        run: nuget restore ./DpdShipper/DpdShipper.sln

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
          
      - name: Build solution and generate NuGet package
        run: |  
          cd DpdShipper/DpdShipper.Api
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: nuget push ./DpdShipper/DpdShipper.Api/out/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}}
